language: node_js
node_js:
  - "10"
branches:
  only:
    - master
install:
  - npm install
  - pip install --user awscli
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng build --prod --aot
deploy:
  provider: s3
  access_key_id:
    secure: kKBLInHwO08nNccr9d5iIy03/aZLVAFTbTS+31xpdfCrqClGxA+QKEo7Iq+iGs6syQlS2IBeNcVhxnKamHu54+YfdwaxYRlf2ZDk6ipu6Z6eXRtsN8o0A6tSy2LYRbDwWDxGpdga4fYJYo53jIB94oEVMYtFvPqO6bfjqk7mCRyqMSQ+7D3eVHghgsZPDxDUWfskOvg3RjVQ9gnQRcvOklY68xg/lwH9FXCIuHDZ7o5c6Jf/4dPo/QpXZSyXlcQEwVyNp4dGD46O5LUYOCtDWLVW1qbxII3GeHuYFVBVGloSRPviK0ifJxRC8jpswGCxxDJT2PvCmhLbchtppEAiwnkmRV4Qn6jMqO+zi3MqHPJaEt2VR9cYnc6Lvfuklt0skrRpJWmQlr9FUbuhH4JZZBd6Eck5udty6QLGBVFFCPAMzo8wiBC8sGxztHk6SefDoT8HRkc+ZrzwZf0SqNz0JiPvI1PS4nrTMwtFcsrp6sb5iBqOQiTB0eYRXWdtA9GmHKtnJzEpjgQGukZdmfbwdFYjCk5kFS0NR5II83PuCRgbClF55Rhph4veybncfruYEHw/ldz1h1iNX1Hf4A3ps0z7YtwIcdJOO2s4CbdVFS/g8pVhU9NqI26M990PcZtft2iQPbb/OrUTyNwcZ+merPjF0JxysmcsoC8JfBz/GhA=
  secret_access_key:
    secure: RP8ai+mH7a/oXO/hKGkErx3OydF+Y5iIiIEg0cgY3/Lp4GyNqGeisZO/doIwmWZz+jGXfgp4vsU9ZnbKRC7SMQorNRMhpyZnutn9hupyKd/imEQG9Ua1T+ZAJozwoRYaLDrFzxvGwliyWR0g6/8zIxe5lHLyrUsEzqaLl97T6GyqTw4hZ5fg9bNoI2sZ69SZfK0N3JHZVI3zRLR98b5+Z+zBvkMhgfU7ptSOTwZsyleGJxfgGzNn+KaDm8zlY9Did5prKEUrnwUJu+PDbUcZHx+oTciTyrU5GqT30DDCYtb/O0eRdWs6MOsOgEFMbSDJAjNUthOGiPCWbICtNeg/9hFv0eSMOpWiEnTU7kD4NzR4PUxwp6IVN0XzOSDbNfQQYJ/U8JAxQ5059nAFhuougfi2w3TTCu8+Ym8l1jB4c3CACn4tFPG5cutUD+zah4ahNjHYwl2a4YMTHADjjsvEUaIEk7TOAqHIrjVRyWvZIRixECxvjkAQz73Jg4M3bJTR3ed3WQhPCT2Iu7kkTvvtUyxvF6zoqNrkbiqFgBkG9ZifgZ3wr3t88oNsw6LxD91n5ixxZLHFG0O92tYUmgGGSScSGBUxU9+VcLhcecG9d2O5edQJxCxH0VH9cC2/wNbpaGh5j5J9tVeONna/M2LyJpMu+TKdklkd/WBu9SmA/xQ=
  bucket: kaustubhk.com
  local_dir: "./dist/web-app/"
  upload_dir: website
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
notifications:
  email:
    on_failure: always
env:
  global:
    - WEBSITE_BUCKET=kaustubhk.com
    - AWS_DEFAULT_REGION=us-east-1
    - AWS_DEFAULT_OUTPUT=json
    - secure: qvjw4J1BfQKlz8b+WTPfEjV0cnAfgQw3HFOs2VdQBYXXp9wSUvOpdl7WEQa01LlI62NC5EqH68kkh5GvXBItyTwYbnjuSlYGl3Oz0kKHDYudk9Ab70tBYpEpTHBh3AG0Unx3xLxItpysJmTfvDQkx01MXt9yvaoyOUcEbNpYjUwLJN0nAzVOvehKcSNv0zEOMUx5b9JOunQtMfaAnQM13cG9WiegB0x+szLx1qAVe4cU095kZNSCNHctgmCoPjgpBRaXLrwtiTwaozBo1rVpbN6Ii3btQZREKDwb0YeeHZ5PLy1z0wW/2+bztu3G6BTNPpfO4h5+0h/hXebMPq0N1YX4ckSSBFgwfK0b7b4GQWf8tg6RwTiVifxZRzMOzMAGNGxxs2TVRJ2S74I+4yJOFNGPfK1rCNMf35uLvBkOVZRBw4meUGWf9P4u8GfzUwpvwm2J7SCx4U29VM3k0IVMz6nd7OAR3+G7cfnVuAWOn+LoU5AVXqeFza4TmjSBQlcPvigLjxmPc6WB7JyMVEhoA3eKXWSoIUqV+QYORSxGRK+KhX89YRY0VH+Pd0RKHsKIrk2ZLxoV/PxhsDRA3p4qdaM8sF6mfmBBIvyFodR/EcBJIZz2C2eyKM7TXIMygWwBQ6VNxSQmap9sjTcWwsDYcjmbHTRsOtOo9rcfyeL7wJo=
    - secure: CivMr9b17nyTpwgLN473SBC7OVd4Ja6Iog0alsR1rlfPGTDMDwpX0nCDL2h4VJzN4XYzhs3kKD/B5G5R+XjPW0KtD5RroT0fnIF4eazvZnooc9j4zJfMAsSy0Reo+OSpsabh/HclQ+Qenb8aefxAepcaYzU0eLQrMrLdeW+0t/dYV6GRX9aI3pQTfyLkTducuLw0VtjeBWWjYxtfXqE3OYl4dk07nlMF6SNSeUqi+SfsFqwQemEzHkfrs+iJ+m5KXxKAse5Jzn8/HtUVMINGgJPwPX/5kHumoSsUjwFpW3RSxaValbGUKr2JxQd4OaJ11kT/pGK1vdsuzt7oqQiTaAx/MEP9P4Ku8Ddv8Ud9m6lWnXatUIXhHTP2UB7Xkwr31zm5ogBf6Pq2ReMGwbOnRMaYljwSmyKSczhd4sTfV+LWw+4PSpkWuJuAMDzZs/zYQ30joJMQvhO4K58b6vV3pBOt5nWKcxprFYH4JOJyG7HmCagrmgpCGZMG3n4ont5SxZ6IdiGgBDquSEdJV49TI2c7LLlRMbaiye6XRCOt0/OmTxW3OdE7mg1lkckfMRa0PPb2hcHYrE7spKk3o7nCJ514OJyWRqzgzyavSQ5n7xClCBJkwUtCDxVS6honFV8y1pwSas11lWgxncCQx5EkC9u3dr6D6C1+yHUNsixiYno=
    - secure: RQKODX3v88ZTvGiK6TZlkhTSPyI0m0m5231lLpiic4sWvj/hmF13DxKLWpfv8FPLfUcMe3iMysTRfnDq0iHzEm2CCZ8BMPYErlZbFzpxQO49GVFLyp0Q0+c+3HKqgvkE9SVmWpUziyst2wY7d3aQwTA65FkozYifZleTuILHewJtIrEEMdlg33EzA1/JfQovSUAzRNMX0MxkwmPkJ1HKa6H9cNpK9FkCpSRZhWkF3B6gqjA4O17aSrz6daA8/UgHsPjDur6gloemowfhV75pRqWtkA24Xq9So2cosAxmRFDHVBbloIhM3DExItN+yly3cfB1nO/f2g7azQc6ad6OZmGpLMa9Aj6nSRM1Ujh7PV1HyAqEpuMQuCGwYiQ+ph6X+LOFTaKwcG1XKIp27TsalcqDKQtNUqZOp8Gg6et1acYwHoFodVWxjZxrmTo8oBhnsrXU6N7JQ3Rf4hC+eOG/KR0jcv+u9ETcGdrEi7rrHuA20O9rRlEdBt752v16SnKm240pqtpSrTmpKDIaHpD+YtdJFsaeONwy461Y2umf3zls8hoKOnjDAUvI5L7JGLc/nDPysi5iEYpleIqp6Ov/D845A4XtjRgxngmgHaE7uNMh9oghuh3f25ONgGctNhMfn6ml3VbuqGZvJ6I0hi3nRfVg2BUZvwZ+MimoYov/sIE=
