language: node_js
node_js:
  - "10"
sudo: required
branches:
  only:
    - master
install:
  - npm install
  - pip install --user awscli
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng build --prod --aot --base-href https://kaustubhk.com
deploy:
  provider: s3
  access_key_id: AKIA3EOSC6CWYSHGJOXP
  secret_access_key:
    secure: fwxk+gKCHjLlmDGkOFUt6DgypzuAvnuA3gtZABrrDzWXkdl4nxGvs6iKDTnK4hYx/EnmbGMZySV+IBPnplRq7d3ozQZJtY8O0qFuGh5j6qtkXzPvsyNTHxf7ET9IDZj2RsUTEYU+RR6bqxkxcGQ2XF1QHAkGvuof+OOvzLc9nrGxt/JtlbqQblWNHG1JKEq1VBprEiyKXKrUhI6BMLm9NRX8xcDWi2KPH8ql/BfIUxB586XVGrWDmM8/SXwEy55/WwWiGNuJ521+UL6LNXaV6ah3aSdfWDqAXZIT2p5A/d48y/VUC0VT8gKVvIeMAwJX9wfmfnSaM7N13gjBPW2MewBCuB4CCmDo1pYiuQ/l5GiGnoBQvzk2/zYVQh0LhoHnW8pABMuKvRMUH63xVolXvm1/klm8WJ238AmHKPd6+hFcGOdxmKvhvV47c2S2BEYzFAYKcQp9zvHqlMS5iSbhrODXmGT1AlFp72jMquahIlQ46C6YDZwW+rTtd7k6rJb/pEStFDeGIAwxdDBpGgtwiXWdeK3EdzGjrsJo2dqxC853C2yGZhWvdHtUoC7FrUF+zKQ68ZzECFEe7KGY24y1nRYebCYRGZrOz9unZv+AQPESnPYoy6clMDS6ep+7sq4aUIJ5nvDJOoI3vuDqq/yd8zc0lnhR4cYtKNDvhl7FeH8=
  bucket: kaustubhk.com
  local-dir: "./dist/web-app/"
  upload-dir: website/
  on:
    repo: KMK-Git/Website-Frontend
after_success:
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
notifications:
  email:
    on_failure: always
env:
  global:
    - secure: Nnvi9BUrmS2i0VdjbuwJnZeM+C247a8VCt3CeQzOUJY3mp2qn1dz/cqG0l14a91A6RpB8zme/RSZX3MhL+uFd4mYlPz/ogNF6uTsSiFWNjW8CC1+jCUZ+owKAlECkoKsl5V2HCAt3M7/jVkI8XphROVsn/++ElWv5VZFbLAfZjH3rUb1olIIY9K/u3xq7pRsEJEkP69XH8XT5/pciL2BRhNpj+ihwhJ1a/A7JKj73b15c9bkyE4Agld0qWImNU5+92zY2Wivr/bisi3gjUU9PGlpB+g0U1tsJ1C+HAyQi3apbXX3q8g2unJh7q24jXrXoSuevaGxobk/Edj2TrfoShyfSwhRhXS6ecXI5LDD1dDds0BE06SWEunBLnrv/RIm1SxKV6iBRDTuQt2D0I9jp5Zifzwibtmxrs+h2pyVyLaU9UgaGQ0THMxS4tb3xGUaqkLX85xxnACdH62G9MpnQEt5kguQ5UpAR+z+GafJvXsDgcXbj5nVpr2SmpMbzW8AQLO33WBOLHlhHqRecCuHjLqiA87V9y35ydnaXAIcxvhYCvFs5l/6xtV+QjmJ2we/im4OBOBktTUai2fDkqGQObJC1q5nQB1caVgzP5zRjrCc/GfavPQIGMdT23DyHfEGOVgNQgxJXvsBjqt0q6ZZQY23+dEoXSDu1DaQnAZLwPo=
